CREATE TABLE Companies(
    CNPJ VARCHAR(14) PRIMARY KEY,
    CompanyName VARCHAR(100) NOT NULL,
    CreationDate DATE NOT NULL,
    CEO VARCHAR(100) NOT NULL,
    Niche VARCHAR(100) NOT NULL
);

CREATE TABLE Departments(
ID INT PRIMARY KEY,
DepartmentName VARCHAR(100) NOT NULL,
HeadOfTheDepartment VARCHAR(100) NOT NULL,
DepartmentDescription VARCHAR(255) NOT NULL,
CompanyCNPJ VARCHAR(14) REFERENCES Companies(CNPJ)
);

CREATE TABLE Employees(
ID UUID PRIMARY KEY,
EmployeeName VARCHAR(100) NOT NULL,
BirthDate DATE NOT NULL,
CPF VARCHAR(11) UNIQUE NOT NULL,
PhoneNumber VARCHAR(11) UNIQUE NOT NULL,
Email VARCHAR(150) UNIQUE NOT NULL,
RoleName VARCHAR(100) NOT NULL,
HireDate DATE NOT NULL,
DepartmentID INT REFERENCES Departments(ID),
CompanyCNPJ VARCHAR(14) REFERENCES Companies(CNPJ)
);

CREATE TABLE Tasks(
ID UUID PRIMARY KEY,
Category VARCHAR(50) NOT NULL,
Priority INT NOT NULL,
TaskName VARCHAR(150),
StartDate DATE NOT NULL,
FinishDate DATE NOT NULL,
Status INT NOT NULL,
DepartmentID INT REFERENCES Departments(ID)
);

CREATE TABLE EmployeeTask(
TaskID UUID REFERENCES Tasks(ID),
EmployeeID UUID REFERENCES Employees(ID)
);